image: golang:1.12.5

stages:
  - test
  - build

test:
  stage: test
  tags: 
    - docker
  script:
    - echo "pwd=${PWD} CI_PROJECT_DIR=$CI_PROJECT_DIR GOPATH=$GOPATH"
    - ls -la
    - go test -v ./...
#    - go fmt $(go list ./... )
  except:
    changes:
      - README.md
      - doc/*

compile:
  stage: build
  tags: 
    - docker
  script:
    - go build -race -ldflags "-extldflags '-static'" ./...
  except:
    changes:
      - README.md
      - doc/*
#  artifacts:
#    paths:
#    - $CI_PROJECT_DIR/cmd/helloworld
