image: golang:1.12.5

variables:
  major_minor_patch: 0.0.${CI_PIPELINE_IID}

stages:
  - test
  - cover
  - build
  - changelog

test:
  stage: test
  tags: 
    - docker
  script:
    - echo "pwd=${PWD} CI_PROJECT_DIR=$CI_PROJECT_DIR GOPATH=$GOPATH"
    - ls -la
    - go test -v ./...
#    - go fmt $(go list ./... )
  except:
    - tags
  except:
    changes:
      - README.md
      - CHANGELOG.md
      - doc/*

coverage:
  stage: cover
  tags:
    - docker
  script:
    - go test -cover ./...

compile:
  stage: build
  tags: 
    - docker
  script:
    - go build -race -ldflags "-extldflags '-static'" ./...
#    - git remote set-url new-origin https://"username:passwd"@gitlab.com/accountname/projectname
#    - git tag -a ${major_minor_patch} -m "version ${major_minor_patch}"
#    - git push origin ${major_minor_patch}
#  except:
#    - tags
#  except:
#    changes:
#      - README.md
#      - doc/*
#  artifacts:
#    paths:
#    - $CI_PROJECT_DIR/cmd/helloworld

changlog:
  image: node:8
  stage: changelog
  script:
    - npm install -g conventional-changelog
    - npm install -g standard-changelog
    - standard-changelog -i CHANGELOG.md -s
    - cat CHANGELOG.md
#    - git add CHANGELOG.md
#    - git commit -m "Add CHANGELOG.md"
#    - git push origin master
