@startuml
participant Client1 order 10
participant OrderBook order 30

Client1 -> OrderBook: New Order (id1 Buy 50 ABC @11.11)
OrderBook --> Client1: New Order Ack (id1)

Client1 -> OrderBook: Cancel Order (id1)
OrderBook --> Client1: Order Cancelled (id1)
@enduml