@startuml
[*] --> PendingOrder: NewOrder
PendingOrder --> New: Accept
PendingOrder --> Rejected: Reject
PendingOrder: Record Event
PendingOrder: Validate Order

Rejected --> [*]: Done
Rejected: Record Event
Rejected: Send Order Reject
Rejected --> CancelRejected: Cancel

New --> Canceled: Cancel
New: Record Event
New: Send Order Ack
New: Add to OrderBook
New: Match orders by price / time
New --> Filled: Match Order
New --> PartiallyFilled: Match Order
New --> New: No Match
New --> New: Amend Order (smaller)
New --> Canceled: Amend Order (smaller)
New --> Expired: Expire

PartiallyFilled --> PartiallyFilled: Match Order
PartiallyFilled --> PartiallyFilled: Amend Order (smaller)
PartiallyFilled --> Canceled: Amend Order (smaller)
PartiallyFilled --> Filled: Match Order
PartiallyFilled --> Canceled: Cancel
PartiallyFilled: Record Event
PartiallyFilled: Update order states
PartiallyFilled: Send fill for both orders
PartiallyFilled --> Expired: Expire

Canceled --> [*]: Done
Canceled --> CancelRejected: Cancel
Canceled: Record Event
Canceled: Update order state
Canceled: Remove from OrderBook
Canceled: Send Order Canceled

Filled --> [*]: Done
Filled: Record Event
Filled: Update order states
Filled: Remove from OrderBook
Filled: Send fill for both orders
Filled --> CancelRejected: Cancel

Expired --> [*]: Done
Expired: Record Event
Expired: Update order states
Expired: Send order Expired
Expired: Remove from OrderBook

CancelRejected --> [*]: Done
CancelRejected: Record Event
CancelRejected: Send Cancel Rejected (reason)

@enduml