@startuml
[*] --> OrderEntryClosed
OrderEntryClosed --> OrderEntryOpen : OpenOrderEntry
OrderEntryClosed --> OrderEntryClosed: NewOrder
OrderEntryClosed --> OrderEntryClosed: NewAuctionOrder
OrderEntryClosed --> OrderEntryClosed: Timer
OrderEntryClosed: (NewOrder) Reject orders
OrderEntryClosed: (NewAuctionOrder) Reject orders
OrderEntryClosed: (Timer) Time to OpenOrderEntry


OrderEntryOpen --> TradingOpen: OpenTrading
OrderEntryOpen --> AuctionOpen: OpenAuction
OrderEntryOpen --> OrderEntryClosed: CloseOrderEntry
OrderEntryOpen --> OrderEntryOpen: NewOrder
OrderEntryOpen --> OrderEntryOpen: NewAuctionOrder
OrderEntryOpen --> OrderEntryOpen: Timer
OrderEntryOpen: (NewOrder) Add limit orders to order book
OrderEntryOpen: (NewOrder) Reject market orders
OrderEntryOpen: (NewAuctionOrder) Add auction orders to auction book
OrderEntryOpen: (Timer) Time to OpenTrading or OpenAuction or CloseOrderEntry

TradingOpen --> TradingOpen: NewOrder
TradingOpen --> TradingOpen: NewAuctionOrder
TradingOpen --> TradingOpen: Timer
TradingOpen --> TradingClosed: CloseTrading
TradingOpen: (OpenTrading) Match all orders on book
TradingOpen: (NewOrder) Match order
TradingOpen: (NewAuctionOrder) Add to auction book
TradingOpen: (Timer) Cancel expired orders
TradingOpen: (Timer) Time to close Trading?

AuctionOpen --> AuctionClosed: CloseAuction
AuctionOpen --> AuctionOpen: NewAuctionOrder
AuctionOpen --> AuctionOpen: NewOrder
AuctionOpen --> AuctionOpen: Timer
AuctionOpen: (NewAuctionOrder) Add to auction book
AuctionOpen: (NewOrder) Add limit orders to auction book
AuctionOpen: (NewOrder) Reject market orders
AuctionOpen: (Timer) Time to close auction?

AuctionClosed --> OrderEntryOpen: OpenOrderEntry
AuctionClosed --> TradingOpen: OpenTrading
AuctionClosed --> AuctionClosed: NewAuctionOrder
AuctionClosed --> AuctionClosed: NewOrder
AuctionClosed: (NewAuctionOrder) Reject Order
AuctionClosed: (NewOrder) Add limit orders to order book
AuctionClosed: (NewOrder) Reject market orders
AuctionClosed: Calculate closing price
AuctionClosed: Match auction and book orders at close
AuctionClosed: Cancel unfilled auction orders
AuctionClosed: OpenTrading or CloseOrderEntry?

TradingClosed --> OrderEntryOpen: OpenOrderEntry
TradingClosed --> AuctionOpen: OpenAuction
TradingClosed --> TradingClosed: NewAuctionOrder
TradingClosed --> TradingClosed: NewOrder
TradingClosed: (NewAuctionOrder) Add to auction book
TradingClosed: (NewOrder) Reject Order
TradingClosed: Cancel day orders
TradingClosed: OpenAuction or CloseOrderEntry?

@enduml