@startuml
[*] --> NoTrading
NoTrading --> TradingOpen: OpenTrading
NoTrading --> AuctionOpen: OpenAuction
NoTrading --> NoTrading: NewOrder
NoTrading --> NoTrading: NewAuctionOrder :TDOD
NoTrading --> NoTrading: Timer
NoTrading: (NewOrder) Add limit orders to order book
NoTrading: (NewAuctionOrder) Add auction orders to auction book
NoTrading: (Timer) Time to OpenTrading or OpenAuction

TradingOpen --> TradingOpen: NewOrder
TradingOpen --> TradingOpen: NewAuctionOrder :TDOD
TradingOpen --> TradingOpen: Timer
TradingOpen --> TradingClosed: CloseTrading
TradingOpen: (OpenTrading) Match all orders on book
TradingOpen: (NewOrder) Match order
TradingOpen: (NewAuctionOrder) Add to auction book
TradingOpen: (Timer) Cancel expired orders
TradingOpen: (Timer) Time to close Trading?

AuctionOpen --> AuctionClosed: CloseAuction
AuctionOpen --> AuctionOpen: NewAuctionOrder
AuctionOpen --> AuctionOpen: NewOrder
AuctionOpen --> AuctionOpen: Timer
AuctionOpen: (NewAuctionOrder) Add to auction book
AuctionOpen: (NewOrder) Add limit orders to order book
AuctionOpen: (Timer) Time to close auction?

AuctionClosed --> NoTrading: NoTrading
AuctionClosed --> TradingOpen: OpenTrading
AuctionClosed: Calculate closing price
AuctionClosed: Match auction and book orders at close
AuctionClosed: Cancel unfilled auction orders
AuctionClosed: OpenTrading or NoTrading?

TradingClosed --> NoTrading: NoTrading
TradingClosed --> AuctionOpen: OpenAuction
TradingClosed: Cancel day orders
TradingClosed: OpenAuction or NoTrading?

@enduml